import Head from 'next/head';

export default function NotFound() {
  return (
    <div>
      <Head>
        <title>Página não encontrada!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="#" />
      </Head>

      <main>
        <h1>404!</h1>
        <p>Página não encontrada.</p>
      </main>
    </div>
  );
}
