import Head from 'next/head';
import { useRouter } from 'next/router';

const Success = () => {
  const router = useRouter();
  const { email } = router.query;

  return (
    <div>
      <Head>
        <title>Sucesso!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="#" />
      </Head>

      <main>
        <h1>Obrigado!</h1>
        <p>{email}</p>
      </main>
    </div>
  );
};

export default Success;
